version: "2"
networks:
  fabricnetwork: {}
services:
  cli:
    image: hyperledger/fabric-tools:${IMAGE_TAG}
    container_name: cli
    tty: true
    environment:
    - CORE_PEER_TLS_ENABLED=true
    - GOPATH=/opt/gopath
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_ID=cli
    working_dir: /opt/ws
    volumes:
    - /var/run/:/host/var/run/
    - ./:/opt/ws
    - ./chaincode/github.com:/opt/gopath/src/github.com
    depends_on:
    - orderer.orderer.net
    - peer0.firstcorp.net
    networks:
    - fabricnetwork
  couch0:
    container_name: couch0
    extends:
      file: base.yaml
      service: couchdb
    ports:
    - 5984:5984
    networks:
    - fabricnetwork
  orderer.orderer.net:
    container_name: orderer.orderer.net
    extends:
      file: base.yaml
      service: orderer
    volumes:
    - ./genesis.block:/var/hyperledger/orderer/genesis.block
    - ./crypto-config/ordererOrganizations/orderer.net/orderers/orderer.orderer.net/msp:/var/hyperledger/orderer/msp
    - ./crypto-config/ordererOrganizations/orderer.net/orderers/orderer.orderer.net/tls/:/var/hyperledger/orderer/tls
    ports:
    - 7050:7050
    networks:
    - fabricnetwork
  peer0.firstcorp.net:
    container_name: peer0.firstcorp.net
    extends:
      file: base.yaml
      service: peer
    environment:
    - CORE_PEER_ID=peer0.firstcorp.net
    - CORE_PEER_ADDRESS=peer0.firstcorp.net:7051
    - CORE_PEER_CHAINCODELISTENADDRESS=peer0.firstcorp.net:7052
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.firstcorp.net:7051
    - CORE_PEER_LOCALMSPID=FirstCorpMSP
    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couch0:5984
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.firstcorp.net:7051
    volumes:
    - /var/run/:/host/var/run/
    - ./crypto-config/peerOrganizations/firstcorp.net/peers/peer0.firstcorp.net/msp:/etc/hyperledger/fabric/msp
    - ./crypto-config/peerOrganizations/firstcorp.net/peers/peer0.firstcorp.net/tls:/etc/hyperledger/fabric/tls
    ports:
    - 7051:7051
    - 7053:7053
    depends_on:
    - couch0
    - orderer.orderer.net
    networks:
    - fabricnetwork
